
server:
  port: 7001

#eureka:
#  instance:
#    hostname: eureka7001
#  client:
#    fetch-registry: false # 不用检索服务 自己是注册中心
#    register-with-eureka: false #不向注册中心注册自己
#    service-url:
#      defaultZone: http://eureka7002:7002/eureka


eureka:
  instance:
    hostname: a.pdt1997.top
  client:
    fetch-registry: false # 不用检索服务 自己是注册中心
    register-with-eureka: false #不向注册中心注册自己
    service-url:
      defaultZone: http://a.pdt1997.top:7001/eureka