################################################################
##项目名称和端口
server:
  port: 10086
spring:
  application:
    name: shop-registry
################################################################
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    ##表示是否从Eureka Server获取注册信息，默认为true 单点就不需要
    fetch-registry: false
    ##是否将自己注册到eureka服务器
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 5000