
#server:
#  port: 7002
#
#eureka:
#  instance:
#    hostname: eureka7002
#  client:
#    fetch-registry: false # 不用检索服务 自己是注册中心
#    register-with-eureka: false #不向注册中心注册自己
#    service-url:
#      defaultZone: http://eureka7001:7001/eureka


server:
  port: 7002

eureka:
  instance:
    hostname: b.pdt1997.top
  client:
    fetch-registry: false # 不用检索服务 自己是注册中心
    register-with-eureka: false #不向注册中心注册自己
    service-url:
      defaultZone: http://a.pdt1997:7001/eureka