
# 命令是  docker stack deploy --compose-file=docker-swarm.yml 【name】

version: '3'
services:
  eureka:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/pdt/eureka:v2 # 镜像名：标签名
    hostname: a.pdt1997.top      # 注册中心的hostname一定要有，且必须和代码中配置文件里的hostname一致
    networks:
      - my_network           # 加入的网络
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7001:7001"             # 映射的端口号，和代码中配置文件里的端口号一致

  order:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/pdt/order:v2
    depends_on:
      - eureka
#      - mysql
#      - redis
    ports:
      - "9001:9001"
    links:
      - eureka
#      - mysql
#      - redis
    networks:
      - my_network           # 加入的网络

#  nginx:
#    image: nginx
#    restart: always
#    networks:
#      - my_network           # 加入的网络
#    environment:
#      - TZ=Asia/Shanghai
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - /docker/nginx/log:/var/log/nginx
#      - /docker/nginx/html:/etc/nginx/html
#      - /docker/nginx/letsencrypt:/etc/letsencrypt  # 放证书的位置

#  mysql:
#    restart: always
#    image: mysql:8
#    ports:
#      - "3306:3306"
#    command:
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1
#      --default-time-zone=+8:00
#    environment:
#      MYSQL_ROOT_PASSWORD: "password" #root登陆密码
#    volumes:
#      - "/docker/mysql/db:/var/lib/mysql"
#      - "/docker/mysql/conf/my.cnf:/etc/my.cnf"
#    networks:
#      - my_network           # 加入的网络

#  redis:
#    restart: always
#    image: redis
#    environment:
#      - TZ=Asia/Shanghai
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - "6379:6379"
#    volumes:
#      - /docker/redis/data:/data
#      - /docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      - my_network           # 加入的网络

#指定网络
networks:
  my_network:
    ##使用已有的网路
    external:
      name: my_network



# *********  文件映射的文件夹一定要自己建好 ************

# nginx.conf

## user  nobody;
#  worker_processes  1;
#  events {
#  worker_connections  1024;
#  }
#
#  http {
#  include       mime.types;
#  default_type  application/octet-stream;
#
#  sendfile        on;
#  #tcp_nopush     on;
#
#  #keepalive_timeout  0;
#  keepalive_timeout  65;
#
#  #gzip  on;
#
#  server {
#  listen       80;
#  server_name  localhost;
#
#  location / {
#  root   html;
#  index  index.html index.htm;
#  }
#  }
#}

# my.cnf
#[mysqld]
#user=mysql
#default-storage-engine=INNODB
#character-set-server=utf8mb4
#[client]
#default-character-set=utf8mb4
#[mysql]
#default-character-set=utf8mb4


# redis.conf
#  requirepass redispassword # 指定密码
#  appendonly yes  # 本地持久化