
# 命令是  docker stack deploy --compose-file=docker-swarm.yml 【name】

version: '3'
services:
  eureka:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/pdt/eureka:v2 # 镜像名：标签名
    hostname: a.pdt1997.top      # 注册中心的hostname一定要有，且必须和代码中配置文件里的hostname一致
    networks:
      - my_network           # 加入的网络
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7001:7001"             # 映射的端口号，和代码中配置文件里的端口号一致

  order9001:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/pdt/order9001:v1
    depends_on:
      - eureka
    ports:
      - "9001:9001"
    links:
      - eureka
    networks:
      - my_network           # 加入的网络
    volumes:
      - /docker/log:/log

  order9002:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/pdt/order9002:v1
    depends_on:
      - eureka
    ports:
      - "9002:9002"
    links:
      - eureka
    networks:
      - my_network           # 加入的网络


#指定网络
networks:
  my_network:
    ##使用已有的网路
    external:
      name: my_network

