server:
  port: 80

eureka:
  client:
    service-url:
      #eureka发现服务的列表
      defaultZone: http://localhost:7001/eureka
    #自己不能注册 自己只需要通过eureka发现服务
    register-with-eureka: false
  instance:
    appname: consumer
    #使用ip索取服务
    prefer-ip-address: true
