server:
  port: 10010
spring:
  application:
    name: api-gateway
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item-service/**    #将商品微服务映射到此路径
    manager-service: /manager-service/**
    zipkin-service: /zipkin-service/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
ribbon:
  ConnectTimeout: 1000 #ribbon链接超时时长
  ReadTimeOut: 3500 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 #熔断超时时长