server:
  port: 8001

spring:
  application:
    name: user

eureka:  #设置eureka注册服务的地址
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: user-8001 #配置服务的别名
    prefer-ip-address: true # 注册的时候使用ip注册