server:
  port: 9002

spring:
  application:
    name: order
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3600ms #超时时间

eureka:  #设置eureka注册服务的地址
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: order-9002 #配置服务的别名
    prefer-ip-address: true # 注册的时候使用ip注册